global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8000', 'localhost:8000', '127.0.0.1:8000']
    metrics_path: '/metrics' 